stages:
    - download-data
    - figures
    - build-pdf


variables:
    DOC: main

download-files:
    stage: download-data

    image: thorbenquast/lcd_hgc_ana_wf
    script:
        - cd data;
        - wget http://cern.ch/tquast/ivcv_irradiated_2021.tar.gz
        - tar -zxvf ivcv_irradiated_2021.tar.gz
        - rm ivcv_irradiated_2021.tar.gz

    artifacts:
        paths:
            - data/ivcv_irradiated_2021
        expire_in: 1 day


compile-rootfigures:
    stage: figures

    image: rootproject/root:6.22.08-centos7
    script:
        - cd plots;
        - source run_rootplots.sh;
    
    artifacts:
        paths:
            - plots/*
        expire_in: 1 week


compile-hexplotfigures:
    stage: figures

    image: thorbenquast/hexplot
    script:
        - source ci/setup.sh;
        - cd plots;
        - source run_hexplots.sh;
    
    artifacts:
        paths:
            - plots/*
        expire_in: 1 week


compile-PDF:
    stage: build-pdf

    # based on 
    # https://hub.docker.com/r/texlive/texlive-full
    # including git
    image: thorbenquast/texlive-full-wgit

    script:
        - wget "https://raw.githubusercontent.com/Hightor/gitinfo2/CTAN/post-xxx-sample.txt" -O generate_gitinfo2
        - chmod +x generate_gitinfo2 && ./generate_gitinfo2
        - latexmk -pdf -pdflatex='pdflatex -file-line-error -synctex=15' ${DOC}
        - ls -latr
    artifacts:
        paths:
            - ${DOC}.pdf
            - ${DOC}.log
        expire_in: 1 week
